### ISSUE TITLE
Source for 1.0.7 ?

### ISSUE THREAD

**Issue by rthery** [EdwardBonnett/c3-vscode-extension#1]
Hello,

First thank you for your work on this extension and its companion addon, very useful to dev in a sane environment ;)

I noticed that the extension currently on VSCode Marketplace is ahead of what's on your repo. Is it possible to push your changes ? I'm thinking of maybe adding a couple of features as I work more with this extension. (and if you need help maintaining it, I'd be glad to!)

**Comment by EdwardBonnett** [comment]
Thanks @rthery, I've just pushed up the source for 1.0.7 - feel free to make any improvements. I'm happy to merge anything back into the main branch and publish

**Comment by rthery** [comment]
Thanks, will be happy to submit PRs then :)
